# pre-commit.ci
ci:
  autofix_commit_msg: |
      [pre-commit.ci] auto fixes from pre-commit hooks

      For more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: 'develop'  # Use 'main' when ready
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: 'weekly'
  skip: []
  submodules: false

# hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    - id: end-of-file-fixer
    - id: debug-statements
    - id: check-yaml
      name: Check YAML
    - id: check-toml
      name: Check TOML
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
    hooks:
    - id: pyupgrade
      args: ["--py39-plus", "--keep-runtime-typing"]

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.5
    hooks:
    - id: ruff
      args:
      - "--fix"
      - "--exit-non-zero-on-fix"
      - "--show-fixes"
      - "--no-unsafe-fixes"

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
    - id: bandit
      args: ["-r"]
      files: ^s7/.*$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
    - id: mypy
      exclude: ^tests/.*$
      additional_dependencies:
      - pydantic>=2,<3
      - types-PyYAML
