services:
  oteapi:
    image: ghcr.io/emmc-asbl/oteapi:${DOCKER_OTEAPI_VERSION:-latest}
    ports:
      - "${PORT:-8080}:8080"
    environment:
      OTEAPI_REDIS_TYPE: redis
      OTEAPI_REDIS_HOST: redis
      OTEAPI_REDIS_PORT: 6379
      OTEAPI_PREFIX: "${OTEAPI_PREFIX:-/api/v1}"
      OTEAPI_EXPOSE_SECRETS: "${OTEAPI_EXPOSE_SECRETS:-True}"
      OTEAPI_AUTHENTICAION_DEPENDENCIES:
      OTEAPI_PLUGIN_PACKAGES: "-v -e /soft7"
    depends_on:
      - redis
    networks:
      - otenet
    volumes:
      - "${PWD}:/soft7"
    stop_grace_period: 1s

  redis:
    image: redis:latest
    volumes:
      - redis-persist:/data
    networks:
      - otenet

volumes:
  redis-persist:

networks:
  otenet:
