name: CI - Update [bot] PR

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - 'main'

jobs:
  add_skip-changelog_label:
    name: Add 'skip-changelog' label
    runs-on: ubuntu-latest

    if: contains(github.actor, '[bot]')

    steps:
    - name: Add 'skip-changelog' label
      uses: actions/github-script@v5
      with:
        script: |
          github.rest.issues.addLabels({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            labels: ['skip-changelog']
          })
